/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoggedInRouteImport } from './routes/_loggedIn'
import { Route as LoggedInIndexRouteImport } from './routes/_loggedIn/index'
import { Route as LoggedInSplatRouteImport } from './routes/_loggedIn/$'
import { Route as apiApiSplatRouteImport } from './routes/(api)/api.$'
import { Route as apiApiRpcSplatRouteImport } from './routes/(api)/api.rpc.$'

const LoggedInRoute = LoggedInRouteImport.update({
  id: '/_loggedIn',
  getParentRoute: () => rootRouteImport,
} as any)
const LoggedInIndexRoute = LoggedInIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LoggedInRoute,
} as any)
const LoggedInSplatRoute = LoggedInSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => LoggedInRoute,
} as any)
const apiApiSplatRoute = apiApiSplatRouteImport.update({
  id: '/(api)/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const apiApiRpcSplatRoute = apiApiRpcSplatRouteImport.update({
  id: '/(api)/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LoggedInIndexRoute
  '/$': typeof LoggedInSplatRoute
  '/api/$': typeof apiApiSplatRoute
  '/api/rpc/$': typeof apiApiRpcSplatRoute
}
export interface FileRoutesByTo {
  '/$': typeof LoggedInSplatRoute
  '/': typeof LoggedInIndexRoute
  '/api/$': typeof apiApiSplatRoute
  '/api/rpc/$': typeof apiApiRpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_loggedIn': typeof LoggedInRouteWithChildren
  '/_loggedIn/$': typeof LoggedInSplatRoute
  '/_loggedIn/': typeof LoggedInIndexRoute
  '/(api)/api/$': typeof apiApiSplatRoute
  '/(api)/api/rpc/$': typeof apiApiRpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$' | '/api/$' | '/api/rpc/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/$' | '/' | '/api/$' | '/api/rpc/$'
  id:
    | '__root__'
    | '/_loggedIn'
    | '/_loggedIn/$'
    | '/_loggedIn/'
    | '/(api)/api/$'
    | '/(api)/api/rpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LoggedInRoute: typeof LoggedInRouteWithChildren
  apiApiSplatRoute: typeof apiApiSplatRoute
  apiApiRpcSplatRoute: typeof apiApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_loggedIn': {
      id: '/_loggedIn'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LoggedInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_loggedIn/': {
      id: '/_loggedIn/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LoggedInIndexRouteImport
      parentRoute: typeof LoggedInRoute
    }
    '/_loggedIn/$': {
      id: '/_loggedIn/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof LoggedInSplatRouteImport
      parentRoute: typeof LoggedInRoute
    }
    '/(api)/api/$': {
      id: '/(api)/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof apiApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(api)/api/rpc/$': {
      id: '/(api)/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof apiApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LoggedInRouteChildren {
  LoggedInSplatRoute: typeof LoggedInSplatRoute
  LoggedInIndexRoute: typeof LoggedInIndexRoute
}

const LoggedInRouteChildren: LoggedInRouteChildren = {
  LoggedInSplatRoute: LoggedInSplatRoute,
  LoggedInIndexRoute: LoggedInIndexRoute,
}

const LoggedInRouteWithChildren = LoggedInRoute._addFileChildren(
  LoggedInRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  LoggedInRoute: LoggedInRouteWithChildren,
  apiApiSplatRoute: apiApiSplatRoute,
  apiApiRpcSplatRoute: apiApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
