/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthSplatRouteImport } from './routes/_auth/$'
import { Route as apiApiSplatRouteImport } from './routes/(api)/api.$'
import { Route as apiApiRpcSplatRouteImport } from './routes/(api)/api.rpc.$'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSplatRoute = AuthSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AuthRoute,
} as any)
const apiApiSplatRoute = apiApiSplatRouteImport.update({
  id: '/(api)/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const apiApiRpcSplatRoute = apiApiRpcSplatRouteImport.update({
  id: '/(api)/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/$': typeof AuthSplatRoute
  '/api/$': typeof apiApiSplatRoute
  '/api/rpc/$': typeof apiApiRpcSplatRoute
}
export interface FileRoutesByTo {
  '/$': typeof AuthSplatRoute
  '/': typeof AuthIndexRoute
  '/api/$': typeof apiApiSplatRoute
  '/api/rpc/$': typeof apiApiRpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_auth/$': typeof AuthSplatRoute
  '/_auth/': typeof AuthIndexRoute
  '/(api)/api/$': typeof apiApiSplatRoute
  '/(api)/api/rpc/$': typeof apiApiRpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$' | '/api/$' | '/api/rpc/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/$' | '/' | '/api/$' | '/api/rpc/$'
  id:
    | '__root__'
    | '/_auth'
    | '/_auth/$'
    | '/_auth/'
    | '/(api)/api/$'
    | '/(api)/api/rpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  apiApiSplatRoute: typeof apiApiSplatRoute
  apiApiRpcSplatRoute: typeof apiApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/$': {
      id: '/_auth/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof AuthSplatRouteImport
      parentRoute: typeof AuthRoute
    }
    '/(api)/api/$': {
      id: '/(api)/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof apiApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(api)/api/rpc/$': {
      id: '/(api)/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof apiApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthSplatRoute: typeof AuthSplatRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSplatRoute: AuthSplatRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  apiApiSplatRoute: apiApiSplatRoute,
  apiApiRpcSplatRoute: apiApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
